workflows:
  ios-build:
    name: Build iOS App
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "ResellPro.xcworkspace"
        XCODE_SCHEME: "ResellPro"
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          pod install
      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - mark@example.com
